### ISSUE TITLE
RangeError('Index out of range') on temperature

### ISSUE THREAD

**Issue by alydersen** [caligo-mentis/smart-bus#11]
Hi!

Thanks again for creating this library!

I've included it in an app that connects HDL and Homey, but some users are getting the following error:
```
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readFloatLE (buffer.js:1154:5)
    at Command.parse (/node_modules/smart-bus/lib/commands.js:1561:29)
    at Command.set (/node_modules/smart-bus/lib/command.js:26:31)
    at new Command (/node_modules/smart-bus/lib/command.js:31:13)
    at Bus.parse (/node_modules/smart-bus/lib/bus.js:116:10)
    at Bus.handler (/node_modules/smart-bus/lib/bus.js:132:22)
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at UDP.onMessage [as onmessage] (dgram.js:659:8)
```

It seems like the https://github.com/caligo-mentis/smart-bus/blob/338e8aebceb0a9028826bd1d83ae4ef89e2132b6/lib/commands.js#L1561 makes an assumption on the length of the buffer that isn't met. Could we instead do what you do in line https://github.com/caligo-mentis/smart-bus/blob/338e8aebceb0a9028826bd1d83ae4ef89e2132b6/lib/commands.js#L1534?

Or, we could catch the errors when parsing fails.

Any preferences? As this is not happening on my system, I can not debug it properly.

Thanks,
Andreas

**Comment by caligo-mentis** [comment]
Hi! Do you know which version of node.js was used?

**Comment by alydersen** [comment]
Seems like Homey uses v8.16.0

**Comment by caligo-mentis** [comment]
It would be nice if you could get a real example of command payload data which produces this error and a model of HDL device. I'll test on my setup if method from `0xE3E8` command could be used as a fallback.

**Comment by alydersen** [comment]
Since it’s happening on closed systems (homey.app), I cannot get debug from it. Working with one of the users to have debugger running at his site at some point. How about wrapping the execution of the parse command to catch any errors and just return a buffer if that happens?

**Comment by caligo-mentis** [comment]
So, i've done some research using PIR sensor (SB-CMS-8in1), DLP panel (HDL-MPTL14.46) and fridge to get negative temperature values.

DLP panel indeed sends float values as described in v1.111 version of docs, but PIR sensor emits only integer part of value, using rest of available bytes for other data (they looks like LUX value, motion sensor and UV switches).

Here is the samples:
- [HDL-MPTL14.46_0xE3E5.log](https://github.com/caligo-mentis/smart-bus/files/4229507/HDL-MPTL14.46_0xE3E5.log)
- [SB-CMS-8in1_0xE3E5.log](https://github.com/caligo-mentis/smart-bus/files/4229508/SB-CMS-8in1_0xE3E5.log)

Easiest way is to fix this issue is to go with logic from `0xE3E8` (also i've fixed error in it).

[v0.5.1](https://www.npmjs.com/package/smart-bus/v/0.5.1) with fix have been published to npm.

Definitely, `Command` should not hide original data and catch parsing errors, this behaviour will be released separately with other API changes.

**Comment by alydersen** [comment]
Perfect - thank you!
