### ISSUE TITLE
support multi device ID

### ISSUE THREAD

**Issue by efa2000** [caligo-mentis/smart-bus#4]
Can I send a command from another device ID (subnet.id)?

**Comment by caligo-mentis** [comment]
@efa2000 you can pass device id and subnet to `SmartBus` constructor:

```js
new SmartBus({
  device: '1.50',
  gateway: '192.168.1.250',
  port: 6000
});
```

Also you should be able to create several instances of `SmartBus` with different device id and subnet, but this behavior is not tested.

**Comment by efa2000** [comment]
I have not tried it, but it seems to me that it will not work out. 
UDP socket, on port 6000 will already be busy and will not allow to create a secondary instance on the same port

**Comment by caligo-mentis** [comment]
@efa2000 sure, you need to specify another port as well

**Comment by efa2000** [comment]
@caligo-mentis HDL IP Gateway can not send at once to several port
It may be possible to add an optional parameter to the sender's address at the time of sending the message?

This would allow creating virtual devices

**Comment by caligo-mentis** [comment]
The problem is that socket will get bound on the same port as specified for HDL Gateway. This is wrong because local port is not important and any free port could be used.

Creating several broadcast UDP sockets just for building message with another sender is also wrong.

As a fast workaround you can try to change `id` and `device` properties of bus instance just before sending, this should work normally even if you are trying to send these messages asynchronously:

```js 
function send(bus, source, target, code, data, callback) {
  const [subnet, id] = source.split('.');
  
  bus.id = id;
  bus.subnet = subnet;

  return bus.send(target, code, data, callback);
}

const bus = new SmartBus(...);

send(bus, '1.30', '1.5', 0xXXXX, ...);
```
